easy_admin:
   entities:
       User :
          disabled_actions: ['new', 'delete']
          class: App\Entity\User
          label: 'Utilisateurs'
          edit:
              title: 'Editer un utilisateur [N°%%entity_id%%]'
              fields:
                  - { type: 'tab' , label: 'Informations utilisateur', icon: 'lock' }
                  - { property: 'username', label: 'Pseudo' }
                  - { property: 'email', label: "Email", type: 'email' }
                  - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN', 'Super administrateur': 'ROLE_SUPER_ADMIN' } } }
                  - { property: 'enabled', label: 'Activation' }
              form_options: { validation_groups: ['Profile'] }
          show:
              fields:
                  - { property: 'username', label: 'Pseudo' }
                  - { property: 'email', label: "Email", type: 'email' }
                  - { property: 'lastLogin', label: 'Dernière connexion' }
                  - { property: 'roles', label: 'Role(s)' }
                  - { property: 'enabled', label: 'Activation' }
                  - { property: 'civility', label: 'Civiliter' }
                  - { property: 'dataUser', label: 'Data' }
                  - { property: 'contents', label: 'Publication' }
                  - { property: 'commentContents', label: 'Commentaire de publication' }
                  - { property: 'reports', label: 'Element reporté' }
              actions:
          list:
              sort: ['id', 'DESC']
              title: "Liste des %%entity_label%%"
              fields:
                  - { property: 'enabled', label: 'Activation' }
                  - { property: 'username', label: 'Pseudo' }
                  - { property: 'email', label: 'Email', type: 'email'}
                  - { property: 'lastLogin', label: 'Dernière connexion' }
                  - { property: 'roles', label: 'Role(s)' }
          search:
            fields: ['username', 'email', 'roles', 'enabled']
